### ISSUE TITLE
Images for GUI

### ISSUE THREAD

**Issue by slepyce** [teamCarel/EyeTracker#12]

**Comment by ValentinHoracek** [comment]
Basic 9 pictures added in commit [7fb5490](https://github.com/teamCarel/EyeTracker/commit/7fb5490fc677f20f3242f110f8b2ace456e4da96)

**Comment by ValentinHoracek** [comment]
More pictures added in commit [603d473](https://github.com/teamCarel/EyeTracker/commit/603d4734b7fa6d1135befb31b939cba855a37b65)
